# https://taskfile.dev
---
version: '3'

vars:
  TO_TAG: '{{ .TO_TAG | default "v1.7.0" }}'
  FROM_TAG: '{{ .FROM_TAG | default "v1.0.0" }}'
  REPO_URL: '{{ .REPO_URL | default "https://github.com/src-d/go-siva" }}'
  TESTDATA_DIR: '{{ .TESTDATA_DIR | default "fixtures" }}'
  OUTPUT: '{{ .OUTPUT | default "output" }}'
  # --paths x --paths y
  PATHS: '{{ .PATHS | default "" }}'

tasks:
  default:
    cmds:
      - task: .test:fixture:output:clean
      - task: test:e2e
      - task: test:fixture:go-siva
      - task: test:fixture:conventional-changelog
      - task: test:fixture:cosmo
      - task: test:fixture:cosmo:dir:router
      - task: test:fixture:cosmo-ops:helm-cosmo
      - task: test:fixture:cosmo-ops:helm-cosmo-router
      - task: build
  .cli:
    internal: true
    cmd: |
      go run main.go \
        --to {{ .TO_TAG }} \
        --from {{ .FROM_TAG }} \
        --repoURL {{ .REPO_URL }} \
        {{ .PATHS }} \
        --output {{ .OUTPUT }}
  build:
    deps:
      - tidy
      - fmt
    cmds:
      - go build -o bin/helm-artifacthub-chglog main.go
  run:
    deps:
      - tidy
      - fmt
    cmds:
      - go run main.go
  tidy:
    cmds:
      - go mod tidy
  fmt:
    cmds:
      - go fmt ./...
  test:
    deps:
      - tidy
    cmds:
      - go test $(go list ./... | grep -v /e2e/)
  test:e2e:
    deps:
      - .test:e2e:testdata
    cmds:
      - echo $REPO_URL
      - go test -v ./e2e

  # test:fixture:[repo]
  test:fixture:go-siva:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/go-siva"
          FROM_TAG: "v1.0.0"
          TO_TAG: "v1.7.0"
          OUTPUT: "{{ .PWD }}/_example-outputs/go-siva.yaml"
  test:fixture:conventional-changelog:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/conventional-changelog"
          FROM_TAG: "v0.0.4"
          TO_TAG: "v1.1.0"
          OUTPUT: "{{ .PWD }}/_example-outputs/conventional-changelog-v0.0.4-v1.1.0.yaml"
  test:fixture:cosmo:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/cosmo"
          FROM_TAG: "router@0.13.0"
          TO_TAG: "router@0.89.2"
          OUTPUT: "{{ .PWD }}/_example-outputs/cosmo-router@0.13.0-router@0.89.2.yaml"
  test:fixture:cosmo-ops:helm-cosmo:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/cosmo-ops"
          FROM_TAG: "helm-cosmo@0.8.10"
          TO_TAG: "helm-cosmo@0.9.0"
          OUTPUT: "{{ .PWD }}/_example-outputs/cosmo-ops-helm-cosmo@0.8.10-helm-cosmo@0.9.0.yaml"
  test:fixture:cosmo-ops:helm-cosmo-router:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/cosmo-ops"
          FROM_TAG: "helm-cosmo-router@0.5.0"
          TO_TAG: "helm-cosmo-router@0.7.8"
          OUTPUT: "{{ .PWD }}/_example-outputs/cosmo-ops-helm-cosmo-router@0.5.0-helm-cosmo-router@0.7.8.yaml"
  test:fixture:cosmo:dir:router:
    deps:
      - .test:fixture
    cmds:
      - task: .cli
        vars:
          REPO_URL: "{{ .PWD }}/fixtures/cosmo"
          FROM_TAG: "router@0.13.0"
          TO_TAG: "router@0.89.2"
          OUTPUT: "{{ .PWD }}/_example-outputs/cosmo-router@0.13.0-router@0.89.2.yaml"
          PATHS: "--paths router/"
  # test helper
  .test:fixture:output:clean:
    internal: true
    cmds:
      - rm -rf {{ .PWD }}/_example-outputs/**
  .test:fixture:output:
    internal: true
    cmds:
      - mkdir -p {{ .PWD }}/_example-outputs
    sources:
      - '{{ .PWD }}/_example-outputs'
  .test:e2e:testdata:
    internal: true
    cmds:
      - mkdir -p {{ .PWD }}/fixtures
      - test -d {{ .PWD }}/fixtures/cosmo || git -C {{ .PWD }}/fixtures clone https://github.com/wundergraph/cosmo.git
      - test -d {{ .PWD }}/fixtures/conventional-changelog || git -C {{ .PWD }}/fixtures clone https://github.com/conventional-changelog/conventional-changelog.git
      - test -d {{ .PWD }}/fixtures/go-siva || git -C {{ .PWD }}/fixtures clone https://github.com/src-d/go-siva.git
      - test -d {{ .PWD }}/fixtures/cosmo-ops || git -C {{ .PWD }}/fixtures clone https://github.com/AndreasZeissner/cosmo-ops
  .test:fixture:
    internal: true
    deps:
      - .test:e2e:testdata
      - tidy
      - fmt
      - .test:fixture:output
