---
name: build
run-name: build by @${{ github.actor }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - develop
    paths:
      - '**.go'
      - '.github/**/*.yaml'
      - 'Taskfile.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dump-gh-context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup go-task / task / taskfile
        uses: rnorton5432/setup-task@v1
      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/go-mod
            fixtures/
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: run default task
        run: task
      - name: run default task
        run: |
          mkdir -p helm/cosmo/charts/router/
          echo "test" > helm/cosmo/charts/router/README.md
          echo "test" > helm/cosmo/README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update helm docs and prepare release'
          file_pattern: 'helm/**/*.md'
          branch: test-branch
          commit_user_name: hardworker-bot
          commit_user_email: bot@wundergraph.com
          commit_author: hardworker-bot <bot@wundergraph.com>
          create_branch: true
